name: 🐜 Bug Report
description: Tell us about something not working properly in the CLI
labels: [ "kind/bug", "priority/needs-triage" ]
body:
  - type: markdown
    attributes:
      value: |
        # Bug Report
        
        Thanks for helping make the deployKF CLI better!
  - type: checkboxes
    attributes:
      label: Checks
      options:
        - label: I have searched the [existing issues](https://github.com/deployKF/cli/issues).
          required: true
  - type: input
    id: deploykf-cli-version
    attributes:
      label: deployKF CLI Version
      placeholder: X.X.X
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: The __context__ the problem occurred in, and an __overview__ of what went wrong.
      placeholder: I was trying to... but then...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Any relevant logs
      placeholder: |
        * Include any relevant log outputs here *
      render: shell